// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.

use crate::rcc::Clocks;
use core::cell::Cell;
use core::cell::RefCell;
use core::marker::PhantomData;
use cortexm33::support;
use kernel::ErrorCode;
use kernel::hil;
use kernel::hil::usb::TransferType;
use kernel::utilities::StaticRef;
use kernel::utilities::cells::OptionalCell;
use kernel::utilities::registers::interfaces::Writeable;
use kernel::utilities::registers::interfaces::{ReadWriteable, Readable};
use kernel::utilities::registers::{
    FieldValue, InMemoryRegister, ReadWrite, register_bitfields, register_structs,
};

// Autogenerated by svd2regs.py
register_structs! {
    /// USB full speed
    pub UsbRegisters {
        /// USB endpoint/channel 0 register
        (0x000 => usb_chep0r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 1 register
        (0x004 => usb_chep1r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 2 register
        (0x008 => usb_chep2r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 3 register
        (0x00C => usb_chep3r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 4 register
        (0x010 => usb_chep4r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 5 register
        (0x014 => usb_chep5r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 6 register
        (0x018 => usb_chep6r: ReadWrite<u32, USB_CHEPXR::Register>),
        /// USB endpoint/channel 7 register
        (0x01C => usb_chep7r: ReadWrite<u32, USB_CHEPXR::Register>),
        (0x020 => _reserved0),

        (0x040 => usb_cntr: ReadWrite<u32, USB_CNTR::Register>),
        /// USB interrupt status register
        (0x044 => usb_istr: ReadWrite<u32, USB_ISTR::Register>),
        /// USB frame number register
        (0x048 => usb_fnr: ReadWrite<u32, USB_FNR::Register>),
        /// USB_DADDR
        (0x04C => usb_daddr: ReadWrite<u32, USB_DADDR::Register>),
        (0x050 => _reserved1),
        /// USB_LPMCSR
        (0x054 => usb_lpmcsr: ReadWrite<u32, USB_LPMCSR::Register>),
        /// USB_BCDR
        (0x058 => usb_bcdr: ReadWrite<u32, USB_BCDR::Register>),
        (0x05C => @END),
    }
}
register_bitfields![u32,
USB_CHEPXR [
    /// Endpoint/channel address
    EA OFFSET(0) NUMBITS(4) [],
    /// Status bits, for transmission transfers
    STATTX OFFSET(4) NUMBITS(2) [],
    /// Data toggle, for transmission transfers
    DTOGTX OFFSET(6) NUMBITS(1) [],
    /// Valid USB transaction transmitted
    VTTX OFFSET(7) NUMBITS(1) [],
    /// endpoint/channel kind
    EPKIND OFFSET(8) NUMBITS(1) [],
    /// USB type of transaction
    UTYPE OFFSET(9) NUMBITS(2) [
        // Added manually:
        Bulk = 0b00,
        Control = 0b01,
        Iso = 0b10,
        Interrupt = 0b11,
    ],
    /// Setup transaction completed
    SETUP OFFSET(11) NUMBITS(1) [],
    /// Status bits, for reception transfers
    STATRX OFFSET(12) NUMBITS(2) [],
    /// Data Toggle, for reception transfers
    DTOGRX OFFSET(14) NUMBITS(1) [],
    /// USB valid transaction received
    VTRX OFFSET(15) NUMBITS(1) [],
    /// Host mode
    DEVADDR OFFSET(16) NUMBITS(7) [],
    /// Host mode
    NAK OFFSET(23) NUMBITS(1) [],
    /// Low speed endpoint  host with HUB only
    LS_EP OFFSET(24) NUMBITS(1) [
        /// Full speed endpoint
        FullSpeedEndpoint = 0,
        /// Low speed endpoint
        LowSpeedEndpoint = 1
    ],
    /// Received error for an OUT/SETUP transaction
    ERR_TX OFFSET(25) NUMBITS(1) [],
    /// Received error for an IN transaction
    ERR_RX OFFSET(26) NUMBITS(1) [],
    /// Three errors for an OUT or SETUP transaction
    THREE_ERR_TX OFFSET(27) NUMBITS(2) [
        /// Less than 3 errors received.
        LessThan3ErrorsReceived = 0,
        /// More than 3 errors received, last error is timeout error.
        MoreThan3ErrorsReceivedLastErrorIsTimeoutError = 1,
        /// More than 3 errors received, last error is data error (CRC error).
        MoreThan3ErrorsReceivedLastErrorIsDataErrorCRCError = 2,
        /// More than 3 errors received, last error is protocol error (invalid PID, false EOP, bitstuffing error, SYNC error).
        B_0x3 = 3
    ],
    /// Three errors for an IN transaction
    THREE_ERR_RX OFFSET(29) NUMBITS(2) [
        /// Less than 3 errors received.
        LessThan3ErrorsReceived = 0,
        /// More than 3 errors received, last error is timeout error.
        MoreThan3ErrorsReceivedLastErrorIsTimeoutError = 1,
        /// More than 3 errors received, last error is data error (CRC error).
        MoreThan3ErrorsReceivedLastErrorIsDataErrorCRCError = 2,
        /// More than 3 errors received, last error is protocol error (invalid PID, false EOP, bitstuffing error, SYNC error).
        B_0x3 = 3
    ]
],
USB_CNTR [
    /// USB Reset
    USBRST OFFSET(0) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// USB core is under reset
        USBCoreIsUnderReset = 1
    ],
    /// Power down
    PDWN OFFSET(1) NUMBITS(1) [
        /// Exit power down.
        ExitPowerDown = 0,
        /// Enter power down mode.
        EnterPowerDownMode = 1
    ],
    /// Suspend state effective
    SUSPRDY OFFSET(2) NUMBITS(1) [
        /// Normal operation
        NormalOperation = 0,
        /// Suspend state
        SuspendState = 1
    ],
    /// Suspend state enable
    SUSPEN OFFSET(3) NUMBITS(1) [
        /// No effect.
        NoEffect = 0,
        /// Enter L1/L2 suspend
        EnterL1L2Suspend = 1
    ],
    /// L2 remote wakeup / resume driver
    L2RES OFFSET(4) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// Send L2 resume signaling to device
        SendL2ResumeSignalingToDevice = 1
    ],
    /// L1 remote wakeup / resume driver
    L1RES OFFSET(5) NUMBITS(1) [
        /// No effect
        NoEffect = 0,
        /// Send 50 us remote-wakeup signaling to host
        Send50UsRemoteWakeupSignalingToHost = 1
    ],
    /// LPM L1 state request interrupt mask
    L1REQM OFFSET(7) NUMBITS(1) [
        /// LPM L1 state request (L1REQ) interrupt disabled.
        LPML1StateRequestL1REQInterruptDisabled = 0,
        /// L1REQ interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Expected start of frame interrupt mask
    ESOFM OFFSET(8) NUMBITS(1) [
        /// Expected start of frame (ESOF) interrupt disabled.
        ExpectedStartOfFrameESOFInterruptDisabled = 0,
        /// ESOF interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Start of frame interrupt mask
    SOFM OFFSET(9) NUMBITS(1) [
        /// SOF interrupt disabled.
        SOFInterruptDisabled = 0,
        /// SOF interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// USB reset request (Device mode) or device connect/disconnect (Host mode) interrupt mask
    RST_DCONM OFFSET(10) NUMBITS(1) [
        /// RESET interrupt disabled.
        RESETInterruptDisabled = 0,
        /// RESET interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Suspend mode interrupt mask
    SUSPM OFFSET(11) NUMBITS(1) [
        /// Suspend mode request (SUSP) interrupt disabled.
        SuspendModeRequestSUSPInterruptDisabled = 0,
        /// SUSP interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Wakeup interrupt mask
    WKUPM OFFSET(12) NUMBITS(1) [
        /// WKUP interrupt disabled.
        WKUPInterruptDisabled = 0,
        /// WKUP interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Error interrupt mask
    ERRM OFFSET(13) NUMBITS(1) [
        /// ERR interrupt disabled.
        ERRInterruptDisabled = 0,
        /// ERR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Packet memory area over / underrun interrupt mask
    PMAOVRM OFFSET(14) NUMBITS(1) [
        /// PMAOVR interrupt disabled.
        PMAOVRInterruptDisabled = 0,
        /// PMAOVR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// Correct transfer interrupt mask
    CTRM OFFSET(15) NUMBITS(1) [
        /// Correct transfer (CTR) interrupt disabled.
        CorrectTransferCTRInterruptDisabled = 0,
        /// CTR interrupt enabled, an interrupt request is generated when the corresponding bit in the USB_ISTR register is set.
        B_0x1 = 1
    ],
    /// 512 byte threshold interrupt mask
    THR512M OFFSET(16) NUMBITS(1) [
        /// 512 byte threshold interrupt disabled
        _512ByteThresholdInterruptDisabled = 0,
        /// 512 byte threshold interrupt enabled
        _512ByteThresholdInterruptEnabled = 1
    ],
    /// Device disconnection mask
    DDISCM OFFSET(17) NUMBITS(1) [
        /// Device disconnection interrupt disabled
        DeviceDisconnectionInterruptDisabled = 0,
        /// Device disconnection interrupt enabled
        DeviceDisconnectionInterruptEnabled = 1
    ],
    /// HOST mode
    HOST OFFSET(31) NUMBITS(1) [
        /// USB Device function
        USBDeviceFunction = 0,
        /// USB host function
        USBHostFunction = 1
    ]
],
USB_ISTR [
    /// Device Endpoint / host channel identification number
    IDN OFFSET(0) NUMBITS(4) [],
    /// Direction of transaction
    DIR OFFSET(4) NUMBITS(1) [],
    /// LPM L1 state request
    L1REQ OFFSET(7) NUMBITS(1) [],
    /// Expected start of frame
    ESOF OFFSET(8) NUMBITS(1) [],
    /// Start of frame
    SOF OFFSET(9) NUMBITS(1) [],
    /// USB reset request (Device mode) or device connect/disconnect (Host mode)
    RST_DCON OFFSET(10) NUMBITS(1) [],
    /// Suspend mode request
    SUSP OFFSET(11) NUMBITS(1) [],
    /// Wakeup
    WKUP OFFSET(12) NUMBITS(1) [],
    /// Error
    ERR OFFSET(13) NUMBITS(1) [],
    /// Packet memory area over / underrun
    PMAOVR OFFSET(14) NUMBITS(1) [],
    /// Completed transfer in host mode
    CTR OFFSET(15) NUMBITS(1) [],
    /// 512 byte threshold interrupt
    THR512 OFFSET(16) NUMBITS(1) [],
    /// Device connection
    DDISC OFFSET(17) NUMBITS(1) [],
    /// Device connection status
    DCON_STAT OFFSET(29) NUMBITS(1) [
        /// No device connected
        NoDeviceConnected = 0,
        /// FS or LS device connected to the host
        FSOrLSDeviceConnectedToTheHost = 1
    ],
    /// Low speed device connected
    LS_DCON OFFSET(30) NUMBITS(1) []
],
USB_FNR [
    /// Frame number
    FN OFFSET(0) NUMBITS(11) [],
    /// Lost SOF
    LSOF OFFSET(11) NUMBITS(2) [],
    /// Locked
    LCK OFFSET(13) NUMBITS(1) [],
    /// Receive dataline status
    RXDM OFFSET(14) NUMBITS(1) [],
    /// Receive data + line status
    RXDP OFFSET(15) NUMBITS(1) []
],
USB_DADDR [
    /// Device address
    ADD OFFSET(0) NUMBITS(7) [],
    /// Enable function
    EF OFFSET(7) NUMBITS(1) []
],
USB_LPMCSR [
    /// LPM support enable
    LPMEN OFFSET(0) NUMBITS(1) [],
    /// LPM token acknowledge enable
    LPMACK OFFSET(1) NUMBITS(1) [
        /// the valid LPM token is NYET.
        TheValidLPMTokenIsNYET = 0,
        /// the valid LPM token is ACK.
        TheValidLPMTokenIsACK = 1
    ],
    /// bRemoteWake value
    REMWAKE OFFSET(3) NUMBITS(1) [],
    /// BESL value
    BESL OFFSET(4) NUMBITS(4) []
],
USB_BCDR [
    /// Battery charging detector (BCD) enable
    BCDEN OFFSET(0) NUMBITS(1) [],
    /// Data contact detection (DCD) mode enable
    DCDEN OFFSET(1) NUMBITS(1) [],
    /// Primary detection (PD) mode enable
    PDEN OFFSET(2) NUMBITS(1) [],
    /// Secondary detection (SD) mode enable
    SDEN OFFSET(3) NUMBITS(1) [],
    /// Data contact detection (DCD) status
    DCDET OFFSET(4) NUMBITS(1) [
        /// data lines contact not detected.
        DataLinesContactNotDetected = 0,
        /// data lines contact detected.
        DataLinesContactDetected = 1
    ],
    /// Primary detection (PD) status
    PDET OFFSET(5) NUMBITS(1) [
        /// no BCD support detected (connected to SDP or proprietary device).
        NoBCDSupportDetectedConnectedToSDPOrProprietaryDevice = 0,
        /// BCD support detected (connected to ACA, CDP or DCP).
        BCDSupportDetectedConnectedToACACDPOrDCP = 1
    ],
    /// Secondary detection (SD) status
    SDET OFFSET(6) NUMBITS(1) [
        /// CDP detected.
        CDPDetected = 0,
        /// DCP detected.
        DCPDetected = 1
    ],
    /// DM pull-up detection status
    PS2DET OFFSET(7) NUMBITS(1) [
        /// Normal port detected (connected to SDP, ACA, CDP or DCP).
        NormalPortDetectedConnectedToSDPACACDPOrDCP = 0,
        /// PS2 port or proprietary charger detected.
        PS2PortOrProprietaryChargerDetected = 1
    ],
    /// DP pull-up / DPDM pull-down
    DPPU_DPD OFFSET(15) NUMBITS(1) []
]
];
pub const USB_BASE: StaticRef<UsbRegisters> =
    unsafe { StaticRef::new(0x4001_6000 as *const UsbRegisters) };

// USBRAM contains a few registers for configuring endpoint buffers, and an area used for allocating buffers
register_structs! {
    pub UsbRamRegisters {
        /// USB channel/endpoint transmit (or receive) buffer descriptor 0 register
        (0x000 => usb_chep_txrxbd_0: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 0 register
        (0x004 => usb_chep_rxtxbd_0: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 1 register
        (0x008 => usb_chep_txrxbd_1: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 1 register
        (0x00C => usb_chep_rxtxbd_1: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 2 register
        (0x010 => usb_chep_txrxbd_2: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 2 register
        (0x014 => usb_chep_rxtxbd_2: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 3 register
        (0x018 => usb_chep_txrxbd_3: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 3 register
        (0x01C => usb_chep_rxtxbd_3: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 4 register
        (0x020 => usb_chep_txrxbd_4: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 4 register
        (0x024 => usb_chep_rxtxbd_4: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 5 register
        (0x028 => usb_chep_txrxbd_5: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 5 register
        (0x02C => usb_chep_rxtxbd_5: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 6 register
        (0x030 => usb_chep_txrxbd_6: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 6 register
        (0x034 => usb_chep_rxtxbd_6: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint transmit (or receive) buffer descriptor 7 register
        (0x038 => usb_chep_txrxbd_7: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// USB channel/endpoint receive (or transmit) buffer descriptor 7 register
        (0x03C => usb_chep_rxtxbd_7: ReadWrite<u32, USB_CHEP_BD::Register>),
        /// Area for buffer allocation
        (0x040 => mem: [ReadWrite<u32>; 496]),
        (0x800 => @END),
    }
}
register_bitfields![u32,
    /// Channel/endpoint buffer descriptor
    USB_CHEP_BD [
        /// Block size (unused for TX)
        BLSIZE OFFSET(31) NUMBITS(1) [],
        /// Number of blocks (unused for TX)
        NUM_BLOCK OFFSET(26) NUMBITS(5) [],
        /// Transmission/reception byte count
        COUNT OFFSET(16) NUMBITS(10) [],
        /// Transmission/reception buffer address
        ADDR OFFSET(0) NUMBITS(16) [],
    ]
];
pub const USBRAM_BASE: StaticRef<UsbRamRegisters> =
    unsafe { StaticRef::new(0x4001_6400 as *const UsbRamRegisters) };

/// The peripheral supports 8 bidirectional endpoints
const EP_COUNT: usize = 8;
/// The USBRAM area has a total length of 2K (including the registers it starts with)
const USBRAM_SIZE: usize = 2048;
/// USBRAM access must be word-aligned (4 bytes)
const USBRAM_ALIGN: usize = 4;

/// Target values for `STATTX`/`STATRX`
#[repr(u8)]
enum StatRXTX {
    Disabled = 0b00,
    Stall = 0b01,
    Nak = 0b10,
    Valid = 0b11,
}

// Adapted from embassy-rs/embassy/embassy-usb-driver/src/lib.rs
/// USB endpoint transfer type
///
/// The values of this enum can be directly cast into `u8` to get the transfer `bmAttributes` transfer type bits
#[derive(Clone, Copy, Eq, PartialEq)]
#[repr(u8)]
pub enum EndpointType {
    /// Control endpoint
    ///
    /// Used for device management
    ///
    /// Only the host can initiate requests
    ///
    /// Usually used only endpoint 0
    Control = 0b00,
    /// Isochronous endpoint
    ///
    /// Used for time-critical unreliable data
    Isochronous = 0b01,
    /// Bulk endpoint
    ///
    /// Used for large amounts of best-effort reliable data
    Bulk = 0b10,
    /// Interrupt endpoint
    ///
    /// Used for small amounts of time-critical reliable data
    Interrupt = 0b11,
}

/// Converts between the kernel's generic `TransferType` and the chip-level `EndpointType`
fn endpoint_type_from(t: TransferType) -> EndpointType {
    match t {
        TransferType::Control => EndpointType::Control,
        TransferType::Isochronous => EndpointType::Isochronous,
        TransferType::Bulk => EndpointType::Bulk,
        TransferType::Interrupt => EndpointType::Interrupt,
    }
}
/// Converts between the chip-level `EndpointType` and the kernel's generic `TransferType`
fn transfer_type_from(t: EndpointType) -> TransferType {
    match t {
        EndpointType::Control => TransferType::Control,
        EndpointType::Isochronous => TransferType::Isochronous,
        EndpointType::Bulk => TransferType::Bulk,
        EndpointType::Interrupt => TransferType::Interrupt,
    }
}

/// Maps an `EndpointType` to values for the `UTYPE` field
fn utype_field(ep_type: EndpointType) -> FieldValue<u32, USB_CHEPXR::Register> {
    match ep_type {
        EndpointType::Control => USB_CHEPXR::UTYPE::Control,
        EndpointType::Isochronous => USB_CHEPXR::UTYPE::Iso,
        EndpointType::Bulk => USB_CHEPXR::UTYPE::Bulk,
        EndpointType::Interrupt => USB_CHEPXR::UTYPE::Interrupt,
    }
}

#[derive(Clone, Copy)]
struct EndpointData {
    /// Type of endpoint
    ep_type: EndpointType,
    /// Whether the IN side is used for this endpoint
    used_in: bool,
    /// Whether the OUT side is used for this endpoint
    used_out: bool,
}

#[derive(Copy, Clone, Eq, PartialEq)]
pub enum Direction {
    /// Host to device (OUT)
    Out,
    /// Device to host (IN)
    In,
}

trait Dir {
    fn dir() -> Direction;
}
/// Marker type for the IN direction
#[derive(Copy, Clone)]
pub enum In {}
impl Dir for In {
    fn dir() -> Direction {
        Direction::In
    }
}
/// Marker type for the OUT direction
#[derive(Copy, Clone)]
pub enum Out {}
impl Dir for Out {
    fn dir() -> Direction {
        Direction::Out
    }
}

/// A region of USBRAM allocated to a single endpoint/direction
///
/// Isochronous endpoints are always double-buffered, so `addr2` holds the second buffer's address for those
/// - the driver picks between `addr`/`addr2` on every transaction based on the current `DTOGTX`/`DTOGRX` bit
/// - see `Usbd::iso_in_next_buffer`/`iso_out_ready_buffer`
#[derive(Copy, Clone)]
struct EndpointBuffer {
    usbram_base: StaticRef<UsbRamRegisters>,
    addr: u16,
    addr2: Option<u16>,
    len: u16,
}
impl EndpointBuffer {
    /// Copies bytes from the given address in USBRAM into the given buffer
    fn read_at(
        &self,
        addr: u16,
        dest: &[InMemoryRegister<u8>],
        len: usize,
    ) -> Result<(), ErrorCode> {
        if len > self.len as usize || len > dest.len() {
            return Err(ErrorCode::SIZE);
        }

        // USBRAM is only word-addressable, so transfers are done 4 bytes at a time
        for i in 0..len.div_ceil(USBRAM_ALIGN) {
            let addr_as_words = addr as usize / USBRAM_ALIGN + i;

            // The address stored in endpoints is absolute; it includes those registers at the start of USBRAM
            // However, the `mem` field needs those words subtracted (2 per endpoint)
            let addr_as_words_corrected = addr_as_words
                .checked_sub(EP_COUNT * 2)
                .ok_or(ErrorCode::INVAL)?;

            let word = self
                .usbram_base
                .mem
                .get(addr_as_words_corrected)
                .ok_or(ErrorCode::INVAL)?;
            let bytes = word.get().to_le_bytes();

            let n = USBRAM_ALIGN.min(len - i * USBRAM_ALIGN);
            for j in 0..n {
                dest[i * USBRAM_ALIGN + j].set(bytes[j]);
            }
        }

        Ok(())
    }

    /// Copies bytes from the given buffer into the given address in USBRAM
    fn write_at(
        &self,
        addr: u16,
        src: &[InMemoryRegister<u8>],
        len: usize,
    ) -> Result<(), ErrorCode> {
        if len > self.len as usize || len > src.len() {
            return Err(ErrorCode::SIZE);
        }

        for i in 0..len.div_ceil(USBRAM_ALIGN) {
            let mut bytes = [0u8; USBRAM_ALIGN];
            let n = USBRAM_ALIGN.min(len - i * USBRAM_ALIGN);
            for j in 0..n {
                bytes[j] = src[i * USBRAM_ALIGN + j].get();
            }

            let addr_as_words = addr as usize / USBRAM_ALIGN + i;
            let addr_as_words_corrected = addr_as_words
                .checked_sub(EP_COUNT * 2)
                .ok_or(ErrorCode::INVAL)?;

            let word = self
                .usbram_base
                .mem
                .get(addr_as_words_corrected)
                .ok_or(ErrorCode::INVAL)?;
            word.set(u32::from_le_bytes(bytes));
        }

        Ok(())
    }

    /// Copies bytes from USBRAM into the given buffer, using the primary (or only) buffer address
    fn read(&self, dest: &[InMemoryRegister<u8>], len: usize) -> Result<(), ErrorCode> {
        self.read_at(self.addr, dest, len)
    }

    /// Copies bytes from the given buffer into USBRAM, using the primary (or only) buffer address
    fn write(&self, src: &[InMemoryRegister<u8>], len: usize) -> Result<(), ErrorCode> {
        self.write_at(self.addr, src, len)
    }
}

#[derive(Clone, Copy, Eq, PartialEq)]
pub struct EndpointAddress {
    pub index: usize,
    pub dir: Direction,
}

#[derive(Copy, Clone)]
struct Endpoint<D> {
    _marker: PhantomData<D>,
    buf: EndpointBuffer,
}

#[derive(Copy, Clone)]
pub struct UsbRam {
    base: StaticRef<UsbRamRegisters>,
}
impl UsbRam {
    pub const fn new(base: StaticRef<UsbRamRegisters>) -> Self {
        Self { base }
    }

    fn get_usb_chep_txrxbd(&self, index: usize) -> Option<&ReadWrite<u32, USB_CHEP_BD::Register>> {
        match index {
            0 => Some(&self.base.usb_chep_txrxbd_0),
            1 => Some(&self.base.usb_chep_txrxbd_1),
            2 => Some(&self.base.usb_chep_txrxbd_2),
            3 => Some(&self.base.usb_chep_txrxbd_3),
            4 => Some(&self.base.usb_chep_txrxbd_4),
            5 => Some(&self.base.usb_chep_txrxbd_5),
            6 => Some(&self.base.usb_chep_txrxbd_6),
            7 => Some(&self.base.usb_chep_txrxbd_7),
            _ => None,
        }
    }
    fn get_usb_chep_rxtxbd(&self, index: usize) -> Option<&ReadWrite<u32, USB_CHEP_BD::Register>> {
        match index {
            0 => Some(&self.base.usb_chep_rxtxbd_0),
            1 => Some(&self.base.usb_chep_rxtxbd_1),
            2 => Some(&self.base.usb_chep_rxtxbd_2),
            3 => Some(&self.base.usb_chep_rxtxbd_3),
            4 => Some(&self.base.usb_chep_rxtxbd_4),
            5 => Some(&self.base.usb_chep_rxtxbd_5),
            6 => Some(&self.base.usb_chep_rxtxbd_6),
            7 => Some(&self.base.usb_chep_rxtxbd_7),
            _ => None,
        }
    }

    /// Writes a TX-style descriptor (`ADDR`/`COUNT`) to the `TXRXBD_n` slot
    ///
    /// For a non-isochronous IN endpoint this is the only buffer, for an isochronous one this is buffer A
    pub fn btable_write_in_len_tx(
        &self,
        index: usize,
        addr: u16,
        len: u16,
    ) -> Result<(), ErrorCode> {
        if addr & 0b11 != 0 {
            return Err(ErrorCode::INVAL);
        }

        let txrxbd = self.get_usb_chep_txrxbd(index).ok_or(ErrorCode::INVAL)?;
        txrxbd.write(USB_CHEP_BD::ADDR.val(addr as u32) + USB_CHEP_BD::COUNT.val(len as u32));
        Ok(())
    }
    /// Writes a TX-style descriptor (`ADDR`/`COUNT`) to the `RXTXBD_n` slot
    ///
    /// This is only meaningful for isochronous IN endpoints, where it is buffer B
    pub fn btable_write_in_len_rx(
        &self,
        index: usize,
        addr: u16,
        len: u16,
    ) -> Result<(), ErrorCode> {
        if addr & 0b11 != 0 {
            return Err(ErrorCode::INVAL);
        }

        let rxtxbd = self.get_usb_chep_rxtxbd(index).ok_or(ErrorCode::INVAL)?;
        rxtxbd.write(USB_CHEP_BD::ADDR.val(addr as u32) + USB_CHEP_BD::COUNT.val(len as u32));
        Ok(())
    }
    /// Writes an OUT-style descriptor (`ADDR`/`BLSIZE`/`NUM_BLOCK`) to the `TXRXBD_n` slot
    ///
    /// This is only meaningful for isochronous OUT endpoints, where it is buffer B
    pub fn btable_write_out_tx(
        &self,
        index: usize,
        addr: u16,
        blsize: bool,
        numblock: u8,
    ) -> Result<(), ErrorCode> {
        if addr & 0b11 != 0 {
            return Err(ErrorCode::INVAL);
        }

        let txrxbd = self.get_usb_chep_txrxbd(index).ok_or(ErrorCode::INVAL)?;
        txrxbd.write(
            USB_CHEP_BD::ADDR.val(addr as u32)
                + USB_CHEP_BD::NUM_BLOCK.val(numblock as u32)
                + USB_CHEP_BD::BLSIZE.val(blsize as u32),
        );
        Ok(())
    }
    /// Writes an OUT-style descriptor (`ADDR`/`BLSIZE`/`NUM_BLOCK`) to the `RXTXBD_n` slot
    ///
    /// For a non-isochronous OUT endpoint this is the only buffer, for an isochronous one this is buffer A
    pub fn btable_write_out_rx(
        &self,
        index: usize,
        addr: u16,
        blsize: bool,
        numblock: u8,
    ) -> Result<(), ErrorCode> {
        if addr & 0b11 != 0 {
            return Err(ErrorCode::INVAL);
        }

        let rxtxbd = self.get_usb_chep_rxtxbd(index).ok_or(ErrorCode::INVAL)?;
        rxtxbd.write(
            USB_CHEP_BD::ADDR.val(addr as u32)
                + USB_CHEP_BD::NUM_BLOCK.val(numblock as u32)
                + USB_CHEP_BD::BLSIZE.val(blsize as u32),
        );
        Ok(())
    }
    /// Reads back `COUNT` from the `TXRXBD_n` slot
    pub fn btable_read_out_len_tx(&self, index: usize) -> Result<u16, ErrorCode> {
        let txrxbd = self.get_usb_chep_txrxbd(index).ok_or(ErrorCode::INVAL)?;
        Ok(txrxbd.read(USB_CHEP_BD::COUNT) as u16)
    }
    /// Reads back `COUNT` from the `RXTXBD_n` slot
    pub fn btable_read_out_len_rx(&self, index: usize) -> Result<u16, ErrorCode> {
        let rxtxbd = self.get_usb_chep_rxtxbd(index).ok_or(ErrorCode::INVAL)?;
        Ok(rxtxbd.read(USB_CHEP_BD::COUNT) as u16)
    }
}

/// State of the control endpoint (endpoint 0)
#[derive(Copy, Clone, PartialEq, Debug)]
enum CtrlState {
    /// Idle, waiting for a SETUP packet
    Init,
    /// Sending IN data for a control read
    ReadIn,
    /// The final IN data packet of a control read has been acknowledged
    ///
    /// Waiting for the host's empty OUT packet that completes the status stage
    ReadStatus,
    /// Receiving OUT data for a control write
    WriteOut,
    /// The empty IN status packet for a control write has been armed
    ///
    /// Waiting for the host to acknowledge it
    WriteStatus,
    /// An empty IN status packet has been armed for a control transfer with no data stage (including SET_ADDRESS)
    ///
    /// Waiting for the host to acknowledge it
    StatusIn,
}

#[derive(Copy, Clone, PartialEq, Debug)]
enum BulkInState {
    /// Ready to accept a request to send a packet
    Init,
    /// A packet has been armed and we're waiting for the host to take it
    InData,
}

#[derive(Copy, Clone, PartialEq, Debug)]
enum BulkOutState {
    /// Ready to receive a packet (`STATRX` valid)
    Init,
    /// A packet was received and handed to the client, which asked to delay accepting more
    ///
    /// `STATRX` is NAK'd until `endpoint_resume_out`
    ///
    /// This state is never entered for isochronous endpoints, since they have no flow control
    OutDelay,
}

#[derive(Copy, Clone, Debug)]
enum EndpointState {
    Disabled,
    Ctrl(CtrlState),
    Bulk(TransferType, Option<BulkInState>, Option<BulkOutState>),
}

pub struct Usbd<'a> {
    registers: StaticRef<UsbRegisters>,
    usbram: UsbRam,
    clocks: OptionalCell<Clocks>,

    endpoint_alloc: RefCell<[EndpointData; EP_COUNT]>,

    /// First free address in endpoint memory, in bytes
    first_free_usbram_addr: Cell<u16>,

    /// Makes `enable`/`enable_as_device` safe to call more than once
    initialized: Cell<bool>,

    /// USBRAM buffers for each endpoint/direction, populated when that direction is enabled
    ep_in_buf: [OptionalCell<EndpointBuffer>; EP_COUNT],
    ep_out_buf: [OptionalCell<EndpointBuffer>; EP_COUNT],

    /// Application buffers, set by the USB client before the corresponding direction is enabled
    slice_in: [OptionalCell<&'a [InMemoryRegister<u8>]>; EP_COUNT],
    slice_out: [OptionalCell<&'a [InMemoryRegister<u8>]>; EP_COUNT],

    state: [Cell<EndpointState>; EP_COUNT],

    /// For endpoint 0's IN side only: whether the packet currently armed (or just acknowledged) is the last one of the current control read
    ctrl_in_last: Cell<bool>,

    /// Set by `endpoint_resume_in` when a new IN packet is requested while one is still transmitting (consumed once the previous one completes)
    ///
    /// Not used for isochronous endpoints, since those always try to queue a new packet as soon as the previous one completes
    request_transmit_in: [Cell<bool>; EP_COUNT],

    address: Cell<u16>,

    client: OptionalCell<&'a dyn hil::usb::Client<'a>>,
}

impl Usbd<'_> {
    pub const fn new(
        usb_base: StaticRef<UsbRegisters>,
        usbram_base: StaticRef<UsbRamRegisters>,
    ) -> Self {
        Self {
            registers: usb_base,
            usbram: UsbRam::new(usbram_base),
            clocks: OptionalCell::empty(),

            endpoint_alloc: RefCell::new(
                [EndpointData {
                    ep_type: EndpointType::Bulk,
                    used_in: false,
                    used_out: false,
                }; EP_COUNT],
            ),

            // The USBRAM area starts with a few configuration registers (2 words per endpoint, so 8 bytes)
            // The area which we can freely use to allocate buffers starts after those
            first_free_usbram_addr: Cell::new(EP_COUNT as u16 * 8),

            initialized: Cell::new(false),

            ep_in_buf: [
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
            ],
            ep_out_buf: [
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
            ],

            slice_in: [
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
            ],
            slice_out: [
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
                OptionalCell::empty(),
            ],

            state: [
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
                Cell::new(EndpointState::Disabled),
            ],

            ctrl_in_last: Cell::new(false),

            request_transmit_in: [
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
                Cell::new(false),
            ],

            address: Cell::new(0),

            client: OptionalCell::empty(),
        }
    }

    pub fn set_clocks(&self, clocks: Clocks) {
        self.clocks.set(clocks);
    }

    fn is_endpoint_available<D: Dir>(&self, index: usize, ep_type: EndpointType) -> bool {
        // EP0 is reserved for control
        if index == 0 && ep_type != EndpointType::Control {
            return false;
        }

        let endpoint_alloc = self.endpoint_alloc.borrow();
        let ep = match endpoint_alloc.get(index) {
            Some(ep) => ep,
            None => return false,
        };

        let used = ep.used_out || ep.used_in;

        if used && ep.ep_type == EndpointType::Isochronous {
            // Isochronous endpoints are always double-buffered
            // Their corresponding endpoint/channel registers are forced to be unidirectional, so do not reuse this index
            return false;
        }

        let used_dir = match D::dir() {
            Direction::Out => ep.used_out,
            Direction::In => ep.used_in,
        };

        !used || (ep.ep_type == ep_type && !used_dir)
    }

    fn align_len_up(len: u16) -> u16 {
        (len as usize).div_ceil(USBRAM_ALIGN) as u16 * USBRAM_ALIGN as u16
    }

    fn calc_len_blsize_numblock(len: u16) -> Result<(u16, bool, u8), ErrorCode> {
        match len {
            2..=60 => {
                let aligned = Self::align_len_up(len);
                Ok((aligned, false, (aligned / 2) as u8))
            }
            61..=1024 => {
                let blocks = len.div_ceil(32);
                Ok((blocks * 32, true, (blocks - 1) as u8))
            }
            _ => Err(ErrorCode::SIZE),
        }
    }

    fn alloc_ep_mem(&self, len: u16) -> Result<u16, ErrorCode> {
        if !(len as usize).is_multiple_of(USBRAM_ALIGN) {
            return Err(ErrorCode::INVAL);
        }

        let addr = self.first_free_usbram_addr.get();
        let next_addr = addr.checked_add(len).ok_or(ErrorCode::NOMEM)?;
        if next_addr > USBRAM_SIZE as u16 {
            return Err(ErrorCode::NOMEM);
        }

        self.first_free_usbram_addr.set(next_addr);

        Ok(addr)
    }

    fn alloc_endpoint<D: Dir>(
        &self,
        ep_type: EndpointType,
        ep_addr: Option<EndpointAddress>,
        max_packet_size: u16,
    ) -> Result<Endpoint<D>, ErrorCode> {
        let index = if let Some(addr) = ep_addr {
            // Use the specified endpoint address
            self.is_endpoint_available::<D>(addr.index, ep_type)
                .then_some(addr.index)
        } else {
            // Find any available endpoint
            (0..EP_COUNT).find(|&i| self.is_endpoint_available::<D>(i, ep_type))
        };

        let mut endpoint_alloc = self.endpoint_alloc.borrow_mut();

        let (index, ep) = match index {
            Some(i) => (i, endpoint_alloc.get_mut(i).ok_or(ErrorCode::INVAL)?),
            None => return Err(ErrorCode::NOMEM),
        };

        ep.ep_type = ep_type;

        let buf = match D::dir() {
            Direction::Out => {
                if ep.used_out {
                    return Err(ErrorCode::ALREADY);
                }
                ep.used_out = true;

                let (len, blsize, numblock) = Self::calc_len_blsize_numblock(max_packet_size)?;
                let addr = self.alloc_ep_mem(len)?;

                self.usbram
                    .btable_write_out_rx(index, addr, blsize, numblock)?;

                let addr2 = if ep_type == EndpointType::Isochronous {
                    // Isochronous endpoints are always double-buffered, allocate a second buffer of the same size
                    let addr2 = self.alloc_ep_mem(len)?;
                    self.usbram
                        .btable_write_out_tx(index, addr2, blsize, numblock)?;
                    Some(addr2)
                } else {
                    None
                };

                EndpointBuffer {
                    addr,
                    addr2,
                    len,
                    usbram_base: self.usbram.base,
                }
            }
            Direction::In => {
                if ep.used_in {
                    return Err(ErrorCode::ALREADY);
                }
                ep.used_in = true;

                let len = Self::align_len_up(max_packet_size);
                let addr = self.alloc_ep_mem(len)?;

                self.usbram.btable_write_in_len_tx(index, addr, 0)?;

                let addr2 = if ep_type == EndpointType::Isochronous {
                    let addr2 = self.alloc_ep_mem(len)?;
                    self.usbram.btable_write_in_len_rx(index, addr2, 0)?;
                    Some(addr2)
                } else {
                    None
                };

                EndpointBuffer {
                    addr,
                    addr2,
                    len,
                    usbram_base: self.usbram.base,
                }
            }
        };

        Ok(Endpoint {
            _marker: PhantomData,
            buf,
        })
    }

    fn ep_register(
        &self,
        index: usize,
    ) -> Result<&ReadWrite<u32, USB_CHEPXR::Register>, ErrorCode> {
        match index {
            0 => Ok(&self.registers.usb_chep0r),
            1 => Ok(&self.registers.usb_chep1r),
            2 => Ok(&self.registers.usb_chep2r),
            3 => Ok(&self.registers.usb_chep3r),
            4 => Ok(&self.registers.usb_chep4r),
            5 => Ok(&self.registers.usb_chep5r),
            6 => Ok(&self.registers.usb_chep6r),
            7 => Ok(&self.registers.usb_chep7r),
            _ => Err(ErrorCode::INVAL),
        }
    }

    /// Modify `USB_CHEPxR`
    /// - `stat_tx`/`stat_rx` are the target `STATTX`/`STATRX` values, or `None` to leave the field unchanged
    /// - `clear_dtog_tx`/`clear_dtog_rx` force the corresponding data toggle to DATA0
    /// - `clear_vtrx`/`clear_vttx` clear the corresponding "correct transfer" flag
    fn write_ep_reg(
        &self,
        index: usize,
        stat_tx: Option<StatRXTX>,
        stat_rx: Option<StatRXTX>,
        clear_dtog_tx: bool,
        clear_dtog_rx: bool,
        clear_vtrx: bool,
        clear_vttx: bool,
    ) -> Result<(), ErrorCode> {
        let ep_type = self
            .endpoint_alloc
            .borrow()
            .get(index)
            .ok_or(ErrorCode::INVAL)?
            .ep_type;
        let epr = self.ep_register(index)?;
        let cur = epr.extract();

        // STATTX/STATRX/DTOGTX/DTOGRX are "write 1 to toggle" bits
        let stat_tx_bits = match stat_tx {
            Some(target) => cur.read(USB_CHEPXR::STATTX) ^ target as u32,
            None => 0,
        };
        let stat_rx_bits = match stat_rx {
            Some(target) => cur.read(USB_CHEPXR::STATRX) ^ target as u32,
            None => 0,
        };
        let dtog_tx_bits = if clear_dtog_tx {
            cur.read(USB_CHEPXR::DTOGTX)
        } else {
            0
        };
        let dtog_rx_bits = if clear_dtog_rx {
            cur.read(USB_CHEPXR::DTOGRX)
        } else {
            0
        };

        // VTRX/VTTX are "write 0 to clear" bits
        epr.write(
            USB_CHEPXR::EA.val(index as u32)
                + utype_field(ep_type)
                + USB_CHEPXR::STATTX.val(stat_tx_bits)
                + USB_CHEPXR::STATRX.val(stat_rx_bits)
                + USB_CHEPXR::DTOGTX.val(dtog_tx_bits)
                + USB_CHEPXR::DTOGRX.val(dtog_rx_bits)
                + USB_CHEPXR::VTRX.val(!clear_vtrx as u32)
                + USB_CHEPXR::VTTX.val(!clear_vttx as u32),
        );

        Ok(())
    }

    fn clear_vtrx(&self, index: usize) -> Result<(), ErrorCode> {
        self.write_ep_reg(index, None, None, false, false, true, false)
    }

    fn clear_vttx(&self, index: usize) -> Result<(), ErrorCode> {
        self.write_ep_reg(index, None, None, false, false, false, true)
    }

    fn bulk_state(
        &self,
        index: usize,
    ) -> Result<(TransferType, Option<BulkInState>, Option<BulkOutState>), ErrorCode> {
        let state = self.state.get(index).ok_or(ErrorCode::INVAL)?.get();
        match state {
            EndpointState::Bulk(t, i, o) => Ok((t, i, o)),
            _ => Err(ErrorCode::INVAL),
        }
    }

    /// For an isochronous OUT endpoint, returns the address and received length of the buffer that was
    /// just filled by hardware, based on the current `DTOGRX` value
    ///
    /// `DTOGRX` is hardware-toggled right after a transaction completes, so its current value tells us
    /// which buffer the application should now read from (see RM0456 Table 737)
    fn iso_out_ready_buffer(
        &self,
        index: usize,
        buf: EndpointBuffer,
    ) -> Result<(u16, u16), ErrorCode> {
        let dtog_rx = self.ep_register(index)?.read(USB_CHEPXR::DTOGRX);

        if dtog_rx == 0 {
            let addr2 = buf.addr2.ok_or(ErrorCode::INVAL)?;
            let len = self.usbram.btable_read_out_len_tx(index)?;
            Ok((addr2, len))
        } else {
            let len = self.usbram.btable_read_out_len_rx(index)?;
            Ok((buf.addr, len))
        }
    }

    /// For an isochronous IN endpoint, returns the address of the buffer the application should
    /// fill next, based on the current `DTOGTX` value, see `iso_out_ready_buffer` for the reasoning
    fn iso_in_next_buffer(&self, index: usize, buf: EndpointBuffer) -> Result<u16, ErrorCode> {
        let dtog_tx = self.ep_register(index)?.read(USB_CHEPXR::DTOGTX);

        if dtog_tx == 0 {
            buf.addr2.ok_or(ErrorCode::INVAL)
        } else {
            Ok(buf.addr)
        }
    }

    pub fn enable(&self) -> Result<(), ErrorCode> {
        // Only the first call has any effect, so it's safe to call more than once
        if self.initialized.get() {
            return Ok(());
        }
        self.initialized.set(true);

        // Exit power-down while keeping USBRST set, wait for the transceiver to stabilize, and only then clear USBRST
        // to release the reset condition
        self.registers
            .usb_cntr
            .write(USB_CNTR::PDWN::ExitPowerDown + USB_CNTR::USBRST::SET);

        // We need a delay of (at least) t_STARTUP=1us
        let sys_freq = self.clocks.get().ok_or(ErrorCode::OFF)?.sys;
        let nop_count = sys_freq.0 / 1_000_000;
        for _ in 0..nop_count {
            support::nop();
        }

        // Release the reset condition, then clear interrupts before enabling the ones we care about
        self.registers.usb_cntr.write(USB_CNTR::PDWN::ExitPowerDown);
        self.registers.usb_istr.set(0);
        self.registers.usb_cntr.write(
            USB_CNTR::PDWN::ExitPowerDown
                + USB_CNTR::RST_DCONM::SET // "Reset request" interrupt
                + USB_CNTR::SUSPM::SET // "Suspend mode" interrupt
                + USB_CNTR::WKUPM::SET // "Wake-up" interrupt
                + USB_CNTR::CTRM::SET, // "Correct transfer" (CTR) interrupt
        );

        Ok(())
    }

    fn enable_control_endpoint(&self) -> Result<(), ErrorCode> {
        let ctrl_buf = self.slice_out[0].map(|b| b).ok_or(ErrorCode::RESERVE)?;
        let max_packet_size = ctrl_buf.len() as u16;

        let ep_out = self.alloc_endpoint::<Out>(
            EndpointType::Control,
            Some(EndpointAddress {
                index: 0,
                dir: Direction::Out,
            }),
            max_packet_size,
        )?;

        let ep_in = self.alloc_endpoint::<In>(
            EndpointType::Control,
            Some(EndpointAddress {
                index: 0,
                dir: Direction::In,
            }),
            max_packet_size,
        )?;

        self.ep_out_buf[0].set(ep_out.buf);
        self.ep_in_buf[0].set(ep_in.buf);

        // Ready to receive SETUP/OUT at all times
        // Idle (NAK) on the IN side until the client has something to send
        self.write_ep_reg(
            0,
            Some(StatRXTX::Nak),
            Some(StatRXTX::Valid),
            true,
            true,
            true,
            true,
        )?;

        self.state[0].set(EndpointState::Ctrl(CtrlState::Init));

        Ok(())
    }

    fn enable_in_endpoint(
        &self,
        transfer_type: TransferType,
        index: usize,
    ) -> Result<(), ErrorCode> {
        let buf_in = self.slice_in[index].map(|b| b).ok_or(ErrorCode::RESERVE)?;
        let max_packet_size = buf_in.len() as u16;
        let ep_type = endpoint_type_from(transfer_type);

        let ep = self.alloc_endpoint::<In>(
            ep_type,
            Some(EndpointAddress {
                index,
                dir: Direction::In,
            }),
            max_packet_size,
        )?;

        self.ep_in_buf[index].set(ep.buf);

        // Isochronous endpoints only support DISABLED/VALID, never NAK, so leave them disabled
        // until the client actually has a packet ready to send
        let idle_stat = if ep_type == EndpointType::Isochronous {
            StatRXTX::Disabled
        } else {
            StatRXTX::Nak
        };
        self.write_ep_reg(index, Some(idle_stat), None, true, false, true, false)?;

        let out_state = match self.state[index].get() {
            EndpointState::Bulk(_, _, o) => o,
            _ => None,
        };

        self.state[index].set(EndpointState::Bulk(
            transfer_type,
            Some(BulkInState::Init),
            out_state,
        ));

        Ok(())
    }

    fn enable_out_endpoint(
        &self,
        transfer_type: TransferType,
        index: usize,
    ) -> Result<(), ErrorCode> {
        let buf_out = self.slice_out[index].map(|b| b).ok_or(ErrorCode::RESERVE)?;
        let max_packet_size = buf_out.len() as u16;
        let ep_type = endpoint_type_from(transfer_type);

        let ep = self.alloc_endpoint::<Out>(
            ep_type,
            Some(EndpointAddress {
                index,
                dir: Direction::Out,
            }),
            max_packet_size,
        )?;
        self.ep_out_buf[index].set(ep.buf);

        // Isochronous OUT endpoints are always ready to receive too, same as bulk/interrupt
        self.write_ep_reg(index, None, Some(StatRXTX::Valid), false, true, false, true)?;

        let in_state = match self.state[index].get() {
            EndpointState::Bulk(_, i, _) => i,
            _ => None,
        };

        self.state[index].set(EndpointState::Bulk(
            transfer_type,
            in_state,
            Some(BulkOutState::Init),
        ));

        Ok(())
    }

    fn arm_ep0_status_in(&self) -> Result<(), ErrorCode> {
        let buf = self.ep_in_buf[0].map(|b| b).ok_or(ErrorCode::RESERVE)?;
        self.usbram.btable_write_in_len_tx(0, buf.addr, 0)?;
        self.write_ep_reg(0, Some(StatRXTX::Valid), None, false, false, false, false)
    }

    fn arm_ep0_out_ready(&self) -> Result<(), ErrorCode> {
        self.write_ep_reg(0, None, Some(StatRXTX::Valid), false, false, false, false)
    }

    fn stall_ep0(&self) -> Result<(), ErrorCode> {
        self.write_ep_reg(
            0,
            Some(StatRXTX::Stall),
            Some(StatRXTX::Stall),
            false,
            false,
            false,
            false,
        )?;

        self.state[0].set(EndpointState::Ctrl(CtrlState::Init));

        Ok(())
    }

    fn transmit_in_ep0(&self) -> Result<(), ErrorCode> {
        match self.client.map(|c| c.ctrl_in(0)) {
            Some(hil::usb::CtrlInResult::Packet(size, last)) => {
                let slice = self.slice_in[0].map(|s| s).ok_or(ErrorCode::RESERVE)?;
                let buf = self.ep_in_buf[0].map(|b| b).ok_or(ErrorCode::RESERVE)?;
                buf.write(slice, size)?;

                self.usbram
                    .btable_write_in_len_tx(0, buf.addr, size as u16)?;
                self.write_ep_reg(0, Some(StatRXTX::Valid), None, false, false, false, false)?;
                self.ctrl_in_last.set(last);

                Ok(())
            }
            Some(hil::usb::CtrlInResult::Delay) => {
                // Nothing ready yet, go idle
                // There's currently no mechanism to resume an EP0 IN transfer once the client is ready
                self.write_ep_reg(0, Some(StatRXTX::Nak), None, false, false, false, false)
            }
            _ => self.stall_ep0(),
        }
    }

    fn handle_setup(&self) -> Result<(), ErrorCode> {
        self.clear_vtrx(0)?;

        let out_buf = self.ep_out_buf[0].map(|b| b).ok_or(ErrorCode::RESERVE)?;
        let slice = self.slice_out[0].map(|s| s).ok_or(ErrorCode::RESERVE)?;
        out_buf.read(slice, 8)?;

        let bm_request_type = slice[0].get();
        let w_length = slice[6].get() as u32 | ((slice[7].get() as u32) << 8);
        let direction_in = (bm_request_type & 0x80) != 0;

        match self.client.map(|c| c.ctrl_setup(0)) {
            Some(hil::usb::CtrlSetupResult::Ok) | Some(hil::usb::CtrlSetupResult::OkSetAddress) => {
                if w_length == 0 {
                    self.arm_ep0_status_in()?;
                    self.state[0].set(EndpointState::Ctrl(CtrlState::StatusIn));
                } else if direction_in {
                    self.state[0].set(EndpointState::Ctrl(CtrlState::ReadIn));
                    self.transmit_in_ep0()?;
                } else {
                    self.arm_ep0_out_ready()?;
                    self.state[0].set(EndpointState::Ctrl(CtrlState::WriteOut));
                }
                Ok(())
            }
            _ => self.stall_ep0(),
        }
    }

    fn handle_ep0_out(&self) -> Result<(), ErrorCode> {
        self.clear_vtrx(0)?;

        match self.state[0].get() {
            EndpointState::Ctrl(CtrlState::WriteOut) => {
                let buf = self.ep_out_buf[0].map(|b| b).ok_or(ErrorCode::RESERVE)?;
                let len = self.usbram.btable_read_out_len_rx(0)? as u32 & 0x3FF;
                let slice = self.slice_out[0].map(|s| s).ok_or(ErrorCode::RESERVE)?;
                buf.read(slice, len as usize)?;

                match self.client.map(|c| c.ctrl_out(0, len)) {
                    Some(hil::usb::CtrlOutResult::Ok) => {
                        self.arm_ep0_status_in()?;
                        self.state[0].set(EndpointState::Ctrl(CtrlState::WriteStatus));
                        Ok(())
                    }
                    Some(hil::usb::CtrlOutResult::Delay) => {
                        self.write_ep_reg(0, None, Some(StatRXTX::Nak), false, false, false, false)
                    }
                    _ => self.stall_ep0(),
                }
            }
            EndpointState::Ctrl(CtrlState::ReadStatus) => {
                // The empty OUT packet that acknowledges the status stage of a control read
                self.client.map(|c| {
                    c.ctrl_status(0);
                    c.ctrl_status_complete(0);
                });

                self.state[0].set(EndpointState::Ctrl(CtrlState::Init));

                Ok(())
            }
            _ => {
                // Unexpected OUT packet for the current state, stall
                self.stall_ep0()
            }
        }
    }

    fn handle_ep0_in_ack(&self) -> Result<(), ErrorCode> {
        self.clear_vttx(0)?;

        match self.state[0].get() {
            EndpointState::Ctrl(CtrlState::ReadIn) => {
                if self.ctrl_in_last.get() {
                    // No more IN data expected until a new SETUP, so NAK further IN tokens
                    // STATRX has been sitting at NAK since the SETUP that started this transfer
                    // Now that the data stage has finished, arm it VALID so the host's status stage OUT ZLP is actually accepted rather than NAK'd forever
                    self.write_ep_reg(
                        0,
                        Some(StatRXTX::Nak),
                        Some(StatRXTX::Valid),
                        false,
                        false,
                        false,
                        false,
                    )?;

                    self.state[0].set(EndpointState::Ctrl(CtrlState::ReadStatus));

                    Ok(())
                } else {
                    self.transmit_in_ep0()
                }
            }
            EndpointState::Ctrl(CtrlState::StatusIn)
            | EndpointState::Ctrl(CtrlState::WriteStatus) => {
                // The empty status IN packet was acknowledged, the control transfer is complete
                self.write_ep_reg(0, Some(StatRXTX::Nak), None, false, false, false, false)?;

                self.client.map(|c| {
                    c.ctrl_status(0);
                    c.ctrl_status_complete(0);
                });

                self.state[0].set(EndpointState::Ctrl(CtrlState::Init));

                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn handle_bulk_out(&self, index: usize) -> Result<(), ErrorCode> {
        self.clear_vtrx(index)?;

        let (transfer_type, in_state, _out_state) = self.bulk_state(index)?;

        let buf = self.ep_out_buf[index]
            .map(|b| b)
            .ok_or(ErrorCode::RESERVE)?;
        let slice = self.slice_out[index].map(|s| s).ok_or(ErrorCode::RESERVE)?;

        let len = if matches!(transfer_type, TransferType::Isochronous) {
            let (addr, len) = self.iso_out_ready_buffer(index, buf)?;
            buf.read_at(addr, slice, len as usize)?;
            len as u32
        } else {
            let len = self.usbram.btable_read_out_len_rx(index)? as u32 & 0x3FF;
            buf.read(slice, len as usize)?;
            len
        };

        match self.client.map(|c| c.packet_out(transfer_type, index, len)) {
            Some(hil::usb::OutResult::Ok) => {
                if !matches!(transfer_type, TransferType::Isochronous) {
                    // Isochronous endpoints have no flow control, STATRX stays VALID at all times
                    self.write_ep_reg(
                        index,
                        None,
                        Some(StatRXTX::Valid),
                        false,
                        false,
                        false,
                        false,
                    )?;
                }

                self.state[index].set(EndpointState::Bulk(
                    transfer_type,
                    in_state,
                    Some(BulkOutState::Init),
                ));

                Ok(())
            }
            Some(hil::usb::OutResult::Delay) => {
                if matches!(transfer_type, TransferType::Isochronous) {
                    // Isochronous endpoints can't be NAK'd, hardware keeps filling the other buffer regardless
                    self.state[index].set(EndpointState::Bulk(
                        transfer_type,
                        in_state,
                        Some(BulkOutState::Init),
                    ));
                } else {
                    self.write_ep_reg(
                        index,
                        None,
                        Some(StatRXTX::Nak),
                        false,
                        false,
                        false,
                        false,
                    )?;

                    self.state[index].set(EndpointState::Bulk(
                        transfer_type,
                        in_state,
                        Some(BulkOutState::OutDelay),
                    ));
                }

                Ok(())
            }
            _ => {
                // Isochronous endpoints only support DISABLED/VALID, there is no STALL to fall back to
                let target = if matches!(transfer_type, TransferType::Isochronous) {
                    StatRXTX::Disabled
                } else {
                    StatRXTX::Stall
                };
                self.write_ep_reg(index, None, Some(target), false, false, false, false)?;

                self.state[index].set(EndpointState::Bulk(
                    transfer_type,
                    in_state,
                    Some(BulkOutState::Init),
                ));

                Ok(())
            }
        }
    }

    fn transmit_in(&self, index: usize) -> Result<(), ErrorCode> {
        let (transfer_type, _in_state, out_state) = self.bulk_state(index)?;

        match self.client.map(|c| c.packet_in(transfer_type, index)) {
            Some(hil::usb::InResult::Packet(size)) => {
                let slice = self.slice_in[index].map(|s| s).ok_or(ErrorCode::RESERVE)?;
                let buf = self.ep_in_buf[index].map(|b| b).ok_or(ErrorCode::RESERVE)?;

                if matches!(transfer_type, TransferType::Isochronous) {
                    let addr = self.iso_in_next_buffer(index, buf)?;
                    buf.write_at(addr, slice, size)?;

                    if addr == buf.addr {
                        self.usbram
                            .btable_write_in_len_tx(index, addr, size as u16)?;
                    } else {
                        self.usbram
                            .btable_write_in_len_rx(index, addr, size as u16)?;
                    }
                } else {
                    buf.write(slice, size)?;
                    self.usbram
                        .btable_write_in_len_tx(index, buf.addr, size as u16)?;
                }

                self.write_ep_reg(
                    index,
                    Some(StatRXTX::Valid),
                    None,
                    false,
                    false,
                    false,
                    false,
                )?;

                self.state[index].set(EndpointState::Bulk(
                    transfer_type,
                    Some(BulkInState::InData),
                    out_state,
                ));

                Ok(())
            }
            Some(hil::usb::InResult::Delay) => {
                if matches!(transfer_type, TransferType::Isochronous) {
                    // Isochronous endpoints can't be NAK'd, whatever was last in the buffer is retransmitted
                    Ok(())
                } else {
                    self.write_ep_reg(index, Some(StatRXTX::Nak), None, false, false, false, false)
                }
            }
            _ => {
                let target = if matches!(transfer_type, TransferType::Isochronous) {
                    StatRXTX::Disabled
                } else {
                    StatRXTX::Stall
                };
                self.write_ep_reg(index, Some(target), None, false, false, false, false)
            }
        }
    }

    fn handle_bulk_in_ack(&self, index: usize) -> Result<(), ErrorCode> {
        self.clear_vttx(index)?;

        let (transfer_type, in_state, out_state) = self.bulk_state(index)?;

        if in_state == Some(BulkInState::InData) {
            self.client.map(|c| c.packet_transmitted(index));

            self.state[index].set(EndpointState::Bulk(
                transfer_type,
                Some(BulkInState::Init),
                out_state,
            ));

            if matches!(transfer_type, TransferType::Isochronous) {
                // Isochronous IN keeps running continuously, always try to queue the next packet
                self.transmit_in(index)
            } else if self.request_transmit_in[index].take() {
                self.transmit_in(index)
            } else {
                self.write_ep_reg(index, Some(StatRXTX::Nak), None, false, false, false, false)
            }
        } else {
            Ok(())
        }
    }

    fn handle_ctr(&self, index: usize) -> Result<(), ErrorCode> {
        let epr = self.ep_register(index)?.extract();

        if epr.is_set(USB_CHEPXR::VTRX) {
            if index == 0 && epr.is_set(USB_CHEPXR::SETUP) {
                self.handle_setup()?;
            } else if index == 0 {
                self.handle_ep0_out()?;
            } else {
                self.handle_bulk_out(index)?;
            }
        }

        if epr.is_set(USB_CHEPXR::VTTX) {
            if index == 0 {
                self.handle_ep0_in_ack()?;
            } else {
                self.handle_bulk_in_ack(index)?;
            }
        }

        Ok(())
    }

    fn handle_bus_reset(&self) -> Result<(), ErrorCode> {
        self.registers
            .usb_daddr
            .write(USB_DADDR::EF::SET + USB_DADDR::ADD.val(0));

        let allocs = *self.endpoint_alloc.borrow();
        for index in 0..EP_COUNT {
            let ep = allocs[index];
            if !ep.used_in && !ep.used_out {
                continue;
            }

            // Isochronous endpoints only support DISABLED/VALID, never NAK
            let stat_tx = if ep.used_in {
                Some(if ep.ep_type == EndpointType::Isochronous {
                    StatRXTX::Disabled
                } else {
                    StatRXTX::Nak
                })
            } else {
                None
            };
            let stat_rx = if ep.used_out {
                Some(StatRXTX::Valid)
            } else {
                None
            };

            self.write_ep_reg(index, stat_tx, stat_rx, ep.used_in, ep.used_out, true, true)?;

            self.state[index].set(if ep.ep_type == EndpointType::Control {
                EndpointState::Ctrl(CtrlState::Init)
            } else {
                EndpointState::Bulk(
                    transfer_type_from(ep.ep_type),
                    if ep.used_in {
                        Some(BulkInState::Init)
                    } else {
                        None
                    },
                    if ep.used_out {
                        Some(BulkOutState::Init)
                    } else {
                        None
                    },
                )
            });

            self.request_transmit_in[index].set(false);
        }

        self.client.map(|c| c.bus_reset());

        Ok(())
    }

    pub fn handle_interrupt(&self) {
        if self.registers.usb_istr.is_set(USB_ISTR::SUSP) {
            self.registers.usb_istr.modify(USB_ISTR::SUSP::CLEAR);
        }

        if self.registers.usb_istr.is_set(USB_ISTR::WKUP) {
            self.registers.usb_istr.modify(USB_ISTR::WKUP::CLEAR);
        }

        if self.registers.usb_istr.is_set(USB_ISTR::RST_DCON) {
            self.registers.usb_istr.modify(USB_ISTR::RST_DCON::CLEAR);
            // A failure here would leave the bus reset half-handled, but there is nowhere to
            // report the error to, since this is the top of the interrupt handling chain
            if self.handle_bus_reset().is_err() {
                return;
            }
        }

        // `ISTR.CTR` is a status bit that stays set as long as any endpoint has a pending `VTRX`/`VTTX`
        // `IDN` reports the lowest-numbered one
        // This loop ensures we don't miss another endpoint's event that was pending at the same time
        while self.registers.usb_istr.is_set(USB_ISTR::CTR) {
            let index = self.registers.usb_istr.read(USB_ISTR::IDN) as usize;
            if self.handle_ctr(index).is_err() {
                return;
            }
        }
    }
}

impl<'a> hil::usb::UsbController<'a> for Usbd<'a> {
    fn set_client(&self, client: &'a dyn hil::usb::Client<'a>) {
        self.client.set(client);
    }

    fn endpoint_set_ctrl_buffer(&self, buf: &'a [InMemoryRegister<u8>]) {
        // The buffer length must be at least 8 and a power of 2
        if buf.len() < 8 || !buf.len().is_power_of_two() {
            return;
        }

        self.slice_in[0].set(buf);
        self.slice_out[0].set(buf);
    }

    fn endpoint_set_in_buffer(&self, endpoint: usize, buf: &'a [InMemoryRegister<u8>]) {
        // The buffer length must be at least 8 and a power of 2
        // The endpoint index must be valid and different from 0 (since that's reserved for control)
        if buf.len() < 8 || !buf.len().is_power_of_two() || endpoint == 0 || endpoint >= EP_COUNT {
            return;
        }

        self.slice_in[endpoint].set(buf);
    }

    fn endpoint_set_out_buffer(&self, endpoint: usize, buf: &'a [InMemoryRegister<u8>]) {
        // The buffer length must be at least 8 and a power of 2
        // The endpoint index must be valid and different from 0 (since that's reserved for control)
        if buf.len() < 8 || !buf.len().is_power_of_two() || endpoint == 0 || endpoint >= EP_COUNT {
            return;
        }

        self.slice_out[endpoint].set(buf);
    }

    fn enable_as_device(&self, speed: hil::usb::DeviceSpeed) {
        match speed {
            // Low speed is not supported
            hil::usb::DeviceSpeed::Low => return,
            hil::usb::DeviceSpeed::Full => {}
        }

        // `enable` returning an error here can't be reported anywhere
        let _ = self.enable();
    }

    fn attach(&self) {
        self.registers.usb_bcdr.modify(USB_BCDR::DPPU_DPD::SET);
    }

    fn detach(&self) {
        self.registers.usb_bcdr.modify(USB_BCDR::DPPU_DPD::CLEAR);
    }

    fn set_address(&self, addr: u16) {
        self.address.set(addr);
    }

    fn enable_address(&self) {
        self.registers
            .usb_daddr
            .modify(USB_DADDR::ADD.val(self.address.get() as u32) + USB_DADDR::EF::SET);
    }

    fn endpoint_in_enable(&self, transfer_type: TransferType, endpoint: usize) {
        match transfer_type {
            TransferType::Control => {
                // Error: there is no IN control endpoint
            }
            TransferType::Bulk | TransferType::Interrupt | TransferType::Isochronous => {
                if endpoint == 0 || endpoint >= EP_COUNT {
                    // Error: bulk/interrupt/isochronous endpoints are endpoints 1 to 7
                    return;
                }

                // `enable_in_endpoint` returning an error here can't be reported anywhere
                let _ = self.enable_in_endpoint(transfer_type, endpoint);
            }
        }
    }

    fn endpoint_out_enable(&self, transfer_type: TransferType, endpoint: usize) {
        match transfer_type {
            TransferType::Control => {
                if endpoint != 0 {
                    // error: only endpoint 0 can be a control endpoint
                    return;
                }

                // `enable_control_endpoint` returning an error here can't be reported anywhere
                let _ = self.enable_control_endpoint();
            }
            TransferType::Bulk | TransferType::Interrupt | TransferType::Isochronous => {
                if endpoint == 0 || endpoint >= EP_COUNT {
                    // Error: bulk/interrupt/isochronous endpoints are endpoints 1 to 7
                    return;
                }

                // `enable_out_endpoint` returning an error here can't be reported anywhere
                let _ = self.enable_out_endpoint(transfer_type, endpoint);
            }
        }
    }

    fn endpoint_in_out_enable(&self, transfer_type: TransferType, endpoint: usize) {
        match transfer_type {
            TransferType::Control => {
                // Error: there is no IN control endpoint
            }
            TransferType::Bulk | TransferType::Interrupt | TransferType::Isochronous => {
                if endpoint == 0 || endpoint >= EP_COUNT {
                    // Error: bulk/interrupt/isochronous endpoints are endpoints 1 to 7
                    return;
                }

                // Only enable the direction(s) that actually have a buffer configured
                let has_in = self.slice_in[endpoint].is_some();
                let has_out = self.slice_out[endpoint].is_some();
                if !has_in && !has_out {
                    // Error: no buffer configured for this endpoint
                    return;
                }
                if has_in {
                    // `enable_in_endpoint` returning an error here can't be reported anywhere
                    let _ = self.enable_in_endpoint(transfer_type, endpoint);
                }
                if has_out {
                    // `enable_out_endpoint` returning an error here can't be reported anywhere
                    let _ = self.enable_out_endpoint(transfer_type, endpoint);
                }
            }
        }
    }

    fn endpoint_resume_in(&self, endpoint: usize) {
        let (_, in_state, _) = match self.bulk_state(endpoint) {
            Ok(s) => s,
            // `bulk_state` returning an error here can't be reported anywhere
            Err(_) => return,
        };

        match in_state {
            Some(BulkInState::Init) => {
                // `transmit_in` returning an error here can't be reported anywhere
                let _ = self.transmit_in(endpoint);
            }
            Some(BulkInState::InData) => self.request_transmit_in[endpoint].set(true),
            None => {
                // Error: no IN direction configured
            }
        }
    }

    fn endpoint_resume_out(&self, endpoint: usize) {
        let (transfer_type, in_state, out_state) = match self.bulk_state(endpoint) {
            Ok(s) => s,
            // `bulk_state` returning an error here can't be reported anywhere
            Err(_) => return,
        };

        match out_state {
            Some(BulkOutState::OutDelay) => {
                // `write_ep_reg` returning an error here can't be reported anywhere
                let _ = self.write_ep_reg(
                    endpoint,
                    None,
                    Some(StatRXTX::Valid),
                    false,
                    false,
                    false,
                    false,
                );

                self.state[endpoint].set(EndpointState::Bulk(
                    transfer_type,
                    in_state,
                    Some(BulkOutState::Init),
                ));
            }
            Some(BulkOutState::Init) => {
                // Already ready to receive, nothing to do
            }
            None => {
                // Error: no OUT direction configured
            }
        }
    }
}
